services:
  postgres:
    image: ghcr.io/t-hajongkim/hira-billing-db:latest
    pull_policy: always
    environment:
      POSTGRES_DB: billing
      POSTGRES_USER: billing
      POSTGRES_PASSWORD: billing
    ports:
      - "5432:5432"
